### ISSUE TITLE
Runtime Error: Undefined Identifier: 'import_code' is unknown in this context [macro-manager.src line 49]

### ISSUE THREAD

**Issue by int96** [cantemizyurek/viper-3.0#2]
I built it and got the error while trying to run viper

Runtime Error: Undefined Identifier: 'import_code' is unknown in this context [macro-manager.src line 49]
![image](https://github.com/cantemizyurek/viper-3.0/assets/12196769/9180806a-3a7f-4520-b01b-2c9844c4d819)

**Comment by cantemizyurek** [comment]
Could you please provide the steps you used to import files into game?

**Comment by cantemizyurek** [comment]
Could you please provide the steps you used to import files into game? It would be better if you can give as much as detail as possible.

**Comment by int96** [comment]
Yeah I used Greybel to install the files small chunks at a time.
and Using copy/paste into Code Editor.

Apon doing a redo I got it to work.. dont know why the first time it compiled and didnt work tho.
Sorry to waste your time.
