### ISSUE TITLE
Building gets Compiler Error

### ISSUE THREAD

**Issue by Phantom3** [cantemizyurek/viper-3.0#3]
EDIT: ON VERSION 0.8.5115

Cloned the repo.
Opened with Visual Studio and built main.
from the build folder imported the installerX.src files into the game.

did build installer(1-6)
did `build main.src /root/bin/`
Compiler Error: got Identifier(Janess1) where EOL is required [line 2454]

**Comment by cantemizyurek** [comment]
Could you please provide the steps you used to import files into game? It would be better if you can give as much as detail as possible.

**Comment by Phantom3** [comment]
Followed the How to install from the repo.
1.Used VS Code to Clone the repo
2.Greybel: Build on main.src
3. Lauanched Grey Hack ( Single Player. Not sure if it matters.)
4. From the build folder imported installed0-6 with Greybel: Import File to Game
5. Built each installer then ran each one.

- `build installer0.src /root/bin`
- `build installer1.src /root/bin`
- `build installer2.src /root/bin`
- `build installer3.src /root/bin`
- `build installer4.src /root/bin`
- `build installer5.src /root/bin`
- `build installer6.src /root/bin`

6. Got a new error on installer6
`root@BitchBox:/root/bin# installer6
Content got appended to "/root/vs/managers/dictionary/list-5.src".
New file "/root/vs/managers/dictionary/list-6.src" got created.
New file "/root/vs/managers/dictionary/dictionary-manager.src" got created.
New file "/root/vs/managers/config/config-manager.src" got created.
New file "/root/vs/jumpfile/jumpfile-text.src" got created.
New file "/root/vs/utils/random-ip.src" got created.
New file "/root/vs/commands.src" got created.
Error when building!`

**Comment by cantemizyurek** [comment]
I wasn't able to reproduce the error. I would recommend trying to rebuild and upload installers again. And checking your greybell settings.
